language: objective-c

xcode_workspace: Example/RUSwiftTypewriterLabel.xcworkspace
xcode_scheme: RUSwiftTypewriterLabel-Example
podfile: Example/Podfile
osx_image: xcode7
xcode_sdk: iphonesimulator9.0
#script: xcodebuild -workspace Example/RUSwiftTypewriterLabel.xcworkspace -scheme RUSwiftTypewriterLabel-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
